server:
  port: 8081

spring:
  application:
    name: api-gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
#          https://authentication-service-production-e98d.up.railway.app #Memmcolapp railway account
          # https://authentication-service-production-dbcd.up.railway.app #my railway account
          # lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/smarte/authentication/**
          filters:
#            - Retry=5  # Retry failed requests up to 5 times
            - RewritePath=/smarte/authentication/(?<remaining>.*), /${remaining}
#            - name: CircuitBreaker
#              args:
#                name: gatewayService  # The name of the circuit breaker
#                fallbackUri: forward:/api/fallback

        - id: organization-service
          uri: lb://ORGANIZATION-SERVICE
          # https://organization-service-production-2c3e.up.railway.app
          # https://organization-service-production-8e17.up.railway.app
          # lb://ORGANIZATION-SERVICE
          predicates:
            - Path=/smarte/organization/**  # Routes all requests starting with /smarte/organization to the organization-service
          filters:
            - RewritePath=/smarte/organization/(?<remaining>.*), /${remaining} # Strip the prefix
#            - CircuitBreaker=name=authenticationCircuitBreaker, fallbackUri=/api/fallback

        - id: email-mqtt-client-service
          uri: lb://EMAIL-MQTT-CLIENT-SERVICE
          # https://email-mqtt-client-service-production-e14b.up.railway.app
          # https://email-mqtt-service-production.up.railway.app
          predicates:
            - Path=/smarte/email/**  # Routes all requests starting with /email to the product-service
          filters:
            - RewritePath=/smarte/email/(?<remaining>.*), /${remaining} # Strip the prefix
#            - CircuitBreaker=name=authenticationCircuitBreaker, fallbackUri=/api/fallback
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # https://eureka-service-production-6595.up.railway.app/eureka/
      # https://eureka-service-production.up.railway.app/eureka/
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    health-check-interval-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


resilience4j:
  circuitbreaker:
    instances:
      gatewayService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s



#server:
#  port: 8081
#
#spring:
#  application:
#    name: api-gateway
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
