server:
  port: 8081
  forward-headers-strategy: native

  ssl:
    enabled: true
    key-store: file:/${WIN_LOCATION}/alfuttaim-gridflex.memmserve.com.pfx
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: ${KEYSTORE_TYPE}
    key-alias: ${KEYSTORE_ALIAS}

spring:
  application:
    name: api-gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      forwarded:
        enabled: true
      routes:

        - id: gridflex-backend-service-v1
          uri: lb://GRIDFLEX-BACKEND-SERVICE
          predicates:
            - Path=/grid-flex/v1/api/**
          filters:
            - RewritePath=/grid-flex/v1/api/(?<remaining>.*), /${remaining} # Strip the prefix- id: gridflex-backend-service

        # Odyssey call route
        - id: gridflex-backend-service-v2
          uri: lb://GRIDFLEX-BACKEND-SERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: swagger-ui
          uri: lb://GRIDFLEX-BACKEND-SERVICE
          predicates:
            - Path=/swagger-ui/**,/gridflex/api-docs/**,/swagger-ui.html

        - id: portal-onboard-service
          uri: lb://PORTAL-ONBOARD-SERVICE
          predicates:
            - Path=/portal/onboard/v1/api/**
          filters:
            - RewritePath=/portal/onboard/v1/api/(?<remaining>.*), /${remaining} # Strip the prefix- id: portal-onboard-servic

        - id: hes-service
          uri: lb://HES-SERVICE
          predicates:
            - Path=/hes/**
          filters:
            - RewritePath=/hes/(?<remaining>.*), /${remaining} # Strip the prefix - id: Hes

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ADDRESS}:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true                # Register using IP instead of hostname
    ip-address: ${spring.cloud.client.ip-address}  # Auto-detects service IP
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      management.port: ${management.server.port:${server.port}}  # Ensure management port is included

management:
  server:
    port: ${server.port}  # Use same port for actuator unless you want a separate port
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
  file:
    name: ${WIN_LOCATION}/logs/api-gateway.log

  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 30
      total-size-cap: 1GB
      file-name-pattern: ${WIN_LOCATION}/logs/api-gateway.%d{yyyy-MM-dd}.%i.log

#  error:
#    include-message: always

resilience4j:
  circuitbreaker:
    instances:
      gatewayService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s