spring.application.name=api-gateway-service
#
## SSL Configuration
#server.ssl.enabled=true
#server.ssl.key-store=classpath:serverkeystore.p12
#server.ssl.key-store-password=Passw0rd
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=my-api-ssl