spring.application.name=api-gateway-service
#
## SSL Configuration
#server.ssl.enabled=true
#server.ssl.key-store=classpath:serverkeystore.p12
#server.ssl.key-store-password=Passw0rd
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=my-api-ssl

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoint.prometheus.access=unrestricted
